import { getUser } from "@/lib/action";
import { userType } from "@/lib/type";
import { Metadata } from "next";
import Link from "next/link";
import { use } from "react";


export const metadata: Metadata = {
    title: "User",
      description: "Generated by create next app",
    };
    

export default function User(){

    const user = use(getUser())
    console.log(user)
    return (
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <h1>User</h1>
          {user.map((user: userType) => (
            <div key={user.id} className="flex gap-10 p-10 text-start">
            <p>{user.name}</p>
            <p>{user.username}</p>
            <p>{user.email}</p>
            <span>{user.company.name}</span>
            <span>{user.address.city}</span>
            <span>{user.address.street}</span>
            <span>{user.phone}</span>
            <Link href={`/user/${user.id}`}>Lire la suite</Link>
            </div>
          ))}
        </main>
      );
}